name = "degree-difference-api"
main = "src/index.ts"
compatibility_date = "2024-10-18"

[vars]
# Add your environment variables here
# RESEND_API_KEY = "..." (These are already in secrets)

[observability]
enabled = true
